name: CI - PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Sanity check repo contents
        run: ls -la
    
      - name: Set up go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
          cache-dependency-path: ./go.sum

      # - name: Run lint checks
      #   uses: golangci/golangci-lint-action@v8
      #   with:
      #     version: 'v2.1.6'
      #     args: "--config=./.golangci.yml"

      # - name: Run go test
      #   shell: bash 
      #   run: |
      #     make test
